apiVersion: v1
kind: Secret
metadata:
  name: quickbite-lg-sc
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMTAuMC4xMS4xODM6NTQzMi9xdWlja2JpdGVkYg==
  SPRING_DATASOURCE_USERNAME: cWJhZG1pbg==
  SPRING_DATASOURCE_PASSWORD: cWJwYXNzd29yZA==
  SPRING_JPA_HIBERNATE_DDL_AUTO: dXBkYXRl
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: b3JnLmhpYmVybmF0ZS5kaWFsZWN0LlBvc3RncmVTUUxEaWFsZWN0
