name: PR Open for Java Application
run-name: ${{ github.actor }} runned this pipeline

# PR Open (một developer tạo pull request -> muốn nộp bài) -> pipeline
on:
  pull_request:
    paths-ignore:
      - '.infra/**' # Ignores changes inside .infra/**
      - '**/*iac-*'
    branches:
      - main
      - master
      - feature


jobs:
  pr-open:
    uses: hoangvankhoa205/centralized-ci/.github/workflows/pr-open-workflow.yml@main




